## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [16]:
import numpy as np
arr = np.linspace(-1.3, 2.5, 65)
print(arr)

[-1.3      -1.240625 -1.18125  -1.121875 -1.0625   -1.003125 -0.94375
 -0.884375 -0.825    -0.765625 -0.70625  -0.646875 -0.5875   -0.528125
 -0.46875  -0.409375 -0.35     -0.290625 -0.23125  -0.171875 -0.1125
 -0.053125  0.00625   0.065625  0.125     0.184375  0.24375   0.303125
  0.3625    0.421875  0.48125   0.540625  0.6       0.659375  0.71875
  0.778125  0.8375    0.896875  0.95625   1.015625  1.075     1.134375
  1.19375   1.253125  1.3125    1.371875  1.43125   1.490625  1.55
  1.609375  1.66875   1.728125  1.7875    1.846875  1.90625   1.965625
  2.025     2.084375  2.14375   2.203125  2.2625    2.321875  2.38125
  2.440625  2.5     ]


2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [18]:
n = int(input())
print(np.array([1, 2, 3] * n))

10
[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


3.	Создайте массив первых 10 нечетных целых чисел.

In [7]:
print(np.arange(1, 20, 2))

[ 1  3  5  7  9 11 13 15 17 19]


4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [6]:
arr = np.ones((10, 10))
arr[1:9, 1:9] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [5]:
arr = np.zeros((8, 8))
arr[::2, ::2] = 1
arr[1::2, 1::2] = 1
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [32]:
def f(n):
    i, j = np.ogrid[:n, :n]
    return i+j
f(10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [33]:
vec1 = np.array([1, 2, 3, 4])
vec2 = np.array([[1], [2], [3], [4]])
matrix1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
matrix2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

print(np.dot(vec1, vec2))
print(np.dot(matrix1, vec2))
print(np.dot(matrix1, matrix2))

[30]
[[30]
 [70]]
[[ 50  60]
 [114 140]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [34]:
num_of_steps = 1/0.05

cosines = np.cos(np.linspace(0, 1, int(num_of_steps)))
sines = np.sin(np.linspace(0, 1, int(num_of_steps)))
result = list(cosines) + list(sines)
result.sort()
print(result)

[0.0, 0.05260728333807213, 0.10506887376594912, 0.15723948186175024, 0.20897462406278547, 0.2601310228046501, 0.3105670033203749, 0.3601428860007191, 0.40872137322898616, 0.4561679296190457, 0.5023511546035125, 0.5403023058681398, 0.547143146340223, 0.5838216399741468, 0.5904198559291864, 0.625724112908743, 0.6320614309590333, 0.6658936781316236, 0.6719525474315213, 0.7042190882928544, 0.7099827291448582, 0.7405942033261461, 0.7460466536513234, 0.7749182843977933, 0.7800444439418607, 0.8070962728972044, 0.8118819450498316, 0.8370390536963741, 0.8414709848078965, 0.8646637019492132, 0.8898937127472434, 0.912659212995635, 0.9328971549228098, 0.9505514906876966, 0.9655733276010717, 0.9779210635311101, 0.9875605021181478, 0.9944649474795756, 0.9986152781425827, 1.0]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [35]:
a = 4*np.random.rand(3,5)-1
a

array([[-0.00848701,  1.20487182,  0.54391699,  2.22365154,  1.53740346],
       [ 1.35953855, -0.06410179,  1.06114006, -0.19279838,  2.1491789 ],
       [ 0.16881638,  1.74647785,  1.45227702,  1.03243862,  0.17304061]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [36]:
summa = np.sum(a)
rows = np.sum(a, axis = 1)
columns = np.sum(a, axis = 0)
avg = np.mean(a, axis = 1)
disp = np.var(a, axis = 1)
otkl = np.std(a, axis = 1)
print(summa, ' - сумму всех элементов матрицы')
print(rows, ' - сумму внутри строк матрицы')
print(columns, ' - сумму внутри столбцов матрицы')
print(avg, ' - среднее значение для каждой строки')
print(disp, ' - дисперсия для каждой строки')
print(otkl, ' - стандартное отклонение для каждой строки')

14.387364626246757  - сумму всех элементов матрицы
[5.5013568  4.31295734 4.57305048]  - сумму внутри строк матрицы
[1.51986792 2.88724788 3.05733408 3.06329177 3.85962297]  - сумму внутри столбцов матрицы
[1.10027136 0.86259147 0.9146101 ]  - среднее значение для каждой строки
[0.60057681 0.78285866 0.42022136]  - дисперсия для каждой строки
[0.77496891 0.884793   0.64824483]  - стандартное отклонение для каждой строки


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [37]:
for i in range(len(a)):
    a[i, :] = (a[i, :] - np.mean(a[i])) / np.std(a[i])
a

array([[-1.43071336,  0.13497375, -0.7179054 ,  1.44958096,  0.56406404],
       [ 0.5616535 , -1.047356  ,  0.22440118, -1.19280989,  1.45411121],
       [-1.15048155,  1.28326169,  0.82941953,  0.18176546, -1.14396513]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [38]:
col = a[:, 2]
sort = col.argsort()
a = a[sort]
a

array([[-1.43071336,  0.13497375, -0.7179054 ,  1.44958096,  0.56406404],
       [ 0.5616535 , -1.047356  ,  0.22440118, -1.19280989,  1.45411121],
       [-1.15048155,  1.28326169,  0.82941953,  0.18176546, -1.14396513]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [41]:
matr_b = np.dot(np.transpose(a), a)
matr_c = np.dot(a, np.transpose(a))
print(matr_b, ' - матрица В')
print(matr_c, ' - матрица С')
"""
Матрицы B и C схожи числом измерений 2 и типом данных значений - float64.
Отличаются они хранящимися в них значениями, размерами и количествами элементов.
"""

[[ 3.68600316 -2.25772881  0.19892069 -2.9529985   1.32580346]
 [-2.25772881  2.76193306  0.732436    1.67820463 -2.91484488]
 [ 0.19892069  0.732436    1.25368081 -1.15757013 -1.02746737]
 [-2.9529985   1.67820463 -1.15757013  3.55711909 -1.12475509]
 [ 1.32580346 -2.91484488 -1.02746737 -1.12475509  3.74126388]]  - матрица В
[[ 5.         -2.01489221  0.84198536]
 [-2.01489221  5.         -3.68434525]
 [ 0.84198536 -3.68434525  5.        ]]  - матрица С


'\nМатрицы B и C схожи числом измерений 2 и типом данных значений - float64.\nОтличаются они хранящимися в них значениями, размерами и количествами элементов.\n'

14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [42]:
np.sum(np.diagonal(matr_b)) + np.sum(np.diagonal(matr_c))

30.0

15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [43]:
print(np.linalg.det(matr_b), ' - определитель матрицы В')
print(np.linalg.det(matr_c), ' - определитель матрицы С')
print(np.linalg.matrix_rank(a), ' - ранг матрицы A')
print(np.linalg.matrix_rank(matr_b), ' - ранг матрицы В')
print(np.linalg.matrix_rank(matr_c), ' - ранг матрицы C')
w_b, v_b = np.linalg.eig(matr_b)
w_c, v_b = np.linalg.eig(matr_c)
print(w_b, ' - спектр матрицы В')
print(w_c, ' - спектр матрицы С')
"""
У всех матриц одинаковый ранг и равен трем.
При перемножении транспонированной матрицы на исходную марицу и исходной на транспонированную ранг не меняется.
При таком перемножении будет меняться определитель и спектр полученной матрицы.
"""

-7.107713181308335e-31  - определитель матрицы В
45.78540573587627  - определитель матрицы С
3  - ранг матрицы A
3  - ранг матрицы В
3  - ранг матрицы C
[ 9.58985382e+00  4.29977098e+00  1.11037521e+00  1.31038091e-16
 -2.17253716e-16]  - спектр матрицы В
[9.58985382 4.29977098 1.11037521]  - спектр матрицы С


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [45]:
np.random.seed(1032202472)
np.random.randint(9)

5

In [64]:
import numpy
import math
def func5(x):
    return numpy.cos(x)**3
a, b = 0, math.pi/2
dx = 0.0001
def solve_integr(func, dx):
    n = int((b - a) / dx)
    x_step = np.linspace(a, b, n)
    meth1 = dx * np.sum(func(x_step))
    meth2 = dx / 2 * (func(x_step[0]) + 2 * np.sum(func(x_step[1:-1])) + func(x_step[-1]))
    meth3 = dx / 3 * (func(x_step[0]) + 2 * np.sum(func(x_step[2:-1:2])) + 4 * np.sum(func(x_step[1:-2:2])) + func(x_step[-1]))
    return meth1, meth2, meth3


print('Решение интеграла 8:', solve_integr(func5, dx)[0], ' (метод прямоугольников)')
print('Решение интеграла 8:', solve_integr(func5, dx)[1], ' (метод трапеций)')
print('Решение интеграла 8:', solve_integr(func5, dx)[2], ' (метод Симпсона)')
'''
При уменьшении dx уменьшается шаг и увеличенивается число точек x_step.Таким образом, увеличивается точность решения.
'''

Решение интеграла 8: 0.6666333429870156  (метод прямоугольников)
Решение интеграла 8: 0.6665833429870155  (метод трапеций)
Решение интеграла 8: 0.6665833429870154  (метод Симпсона)


In [65]:
def func9(x):
    return 1 / np.sqrt(2 + 3 * x - 2 * x ** 2, where=x != 2)
a, b = 3/4, 2
dx = 0.0001
def solve_integr(func, dx):
    n = int((b - a) / dx)
    x_step = np.linspace(a, b, n)
    meth1 = dx * np.sum(func(x_step))
    meth2 = dx / 2 * (func(x_step[0]) + 2 * np.sum(func(x_step[1:-1])) + func(x_step[-1]))
    meth3 = dx / 3 * (func(x_step[0]) + 2 * np.sum(func(x_step[2:-1:2])) + 4 * np.sum(func(x_step[1:-2:2])) + func(x_step[-1]))
    return meth1, meth2, meth3

print('Решение интеграла 9:', solve_integr(func9, dx)[0], ' (метод прямоугольников)')
print('Решение интеграла 9:', solve_integr(func9, dx)[1],' (метод трапеций)')
print('Решение интеграла 9:', solve_integr(func9, dx)[2],  ' (метод Симпсона)')

Решение интеграла 9: 1.1041419998928388  (метод прямоугольников)
Решение интеграла 9: 1.1041172156215913  (метод трапеций)
Решение интеграла 9: 1.1032101773676126  (метод Симпсона)
